### PR TITLE
Add software primer page

### LINKED ISSUE #498: Add primer on software requirements to analysis docs
With #458 and #494, software environment docs are going to be moved out of the `contributing-to-analyses` section. However, this information is still important to communicate somewhere where we introduce analyses. We should therefore add a "primer" page briefly introducing software environments into the `contributing-to-analyses/analysis-modules` section, alongside the compute docs which are moving up there as well (#488).

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #498 
Related to #458 
See #506 for a little more context

---

This PR adds a short "primer" page on software dependencies to the analysis page. I added this to `mkdocs` as well to check formatting since I used buttons! I also did a bit of rearrangement of the conda doc that went in in #507 - two of the headers were the wrong level, and I updated the order so that "using an existing environment" comes after all instructions for creating/managing in the first place.

Noting I indeed would also like for @dvenprasad to have a look here for any feedback on the language as it relates to our goal of making it easier for contributors to find docs on adding dependencies.

Edit: I also want to note that a lot of the language here is very similar (..the same?) as that in this new managing software index file: https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/reproducibility-docs/docs/ensuring-repro/managing-software/index.md. I think this repetition is probably good, do you?

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
> Edit: I also want to note that a lot of the language here is very similar (..the same?) as that in this new managing software index file: https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/reproducibility-docs/docs/ensuring-repro/managing-software/index.md. I think this repetition is probably good, do you?

I have not looked at the files changed yet but my sense is yes, repetition is good as long as things do not conflict. So consider how likely it is that conflicting information would pop up as these are maintained over time!

**Review by jaclyn-taroni — APPROVED** [review]
This looks good to me, but please see my general comment about repeating ourselves: https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/511#issuecomment-2155085131

**Comment by sjspielman** [comment]
> So consider how likely it is that conflicting information would pop up as these are maintained over time!

Conflicting information would occur in this case if we were move away from using conda and renv in the first place....and if that happens we have bigger "problems"! So, this one seems like good repetition to me.

**Review by dvenprasad — APPROVED** [review]
LGTM! 🐌 🐌 🐌 

(You have actually hit the submit button for the comment to go through. I know, shocking! 🤦‍♀️ )

**Pull request merged**
