### PR TITLE
Bump mkdocs and update links action

### PR DESCRIPTION
**Pull request by sjspielman**
I recently updated my local version of `material-mkdocs`, and found that this updated version flags bad _anchor links_ which had not been flagged previously. After playing around with this a bit in the now-closed #545, I realized that in addition to bumping `mkdocs-material`, I also needed to update the `check-links.yml` GHA itself to also grab anchor link warning messages. This GHA indeed failed as expected: https://github.com/AlexsLemonade/OpenScPCA-analysis/actions/runs/9683208495/job/26718098940

This PR takes care of all these items:
- Fixes the bad anchor links we had missed
- Bumps the `mkdocs-material` and `mkdocs` versions to versions that I know actually tell you about bad anchor links
  - Let me know if I was a bit too prescriptive with the `mkdocs-material` patch version here? 
- Updates the GHA to catch bad anchor links as well as bad relative links

Edit: One additional question I have is whether we actually don't want the links action to be _required_ to pass before merging into `main`. During docs development, we may actually expect some `#STUB_LINKS`.  We don't necessarily want that to hold up merging into a feature branch like `reproducibility-docs`, but we definitely don't want bad links going into `main`. I don't have the permissions to make this change though, so if we want to make it we can tag in someone else who can add that protection rule.

### CODE REVIEW

**Comment by allyhawkins** [comment]
> Edit: One additional question I have is whether we actually don't want the links action to be required to pass before merging into main. During docs development, we may actually expect some #STUB_LINKS. We don't necessarily want that to hold up merging into a feature branch like reproducibility-docs, but we definitely don't want bad links going into main. I don't have the permissions to make this change though, so if we want to make it we can tag in someone else who can add that protection rule.

I would agree that we don't want things that are broken being merged into `main`, so I would keep the check there. I think if you want to make the check run but don't require it to pass on feature branches then we do need to tag in someone to update branch protection. I assume it's turned on for `reproducibility-docs` given merging being blocked here, so maybe we adjust to run the CI but it doesn't have to pass CI until it is merged into `main`?

**Comment by sjspielman** [comment]
> I assume it's turned on for reproducibility-docs given merging being blocked here, so maybe we adjust to run the CI but it doesn't have to pass CI until it is merged into main?

Yes, this is what I was thinking!

**Comment by sjspielman** [comment]
Noting that the failure in https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/546/commits/7192b2396482be684014558363fb3724ec48f279 is for an _expected_ stub link which can be updated once #533 goes in.

**Review by allyhawkins — APPROVED** [review]
This looks good to me, but we just need to update branch protection rules or wait for #533

**Comment by allyhawkins** [comment]
> This looks good to me, but we just need to update branch protection rules or wait for #533

Actually it looks like checks aren't required to pass so we are good to go.

**Comment by sjspielman** [comment]
> Actually it looks like checks aren't required to pass so we are good to go.

Ah, indeed! I was just on autopilot assuming they were 😬

**Pull request merged**
